### ISSUE TITLE
Version 1.2.0 is missing Java classes

### ISSUE THREAD

**Issue by bmorris591** [russellwhitaker/uap-clj#28]
On upgrading to the newest version, 1.2.0, my Java project fails to compile.

From examining the contents of the `.jar` file downloaded from Maven, it looks as though the Java classes for the native Java API were not generated in this build.

**Comment by russellwhitaker** [comment]
@bmorris591 hi there; sorry, I never saw the notification of your issue here (this was around the time I was at Clojure/West, thereabouts). Would you please include the full output of your attempt to mvn build the project?

**Comment by bmorris591** [comment]
I didn't try and build the project - I just added the Maven dependency on [version 1.2.0](https://clojars.org/uap-clj) to my Java project.

At that point, the existing code failed to compile - I couldn't locate the `.class` files for the Java API mentioned in the documentation anywhere in the Jar.

My guess would be that they were not packaged with this release.

**Comment by russellwhitaker** [comment]
@bmorris591 just to be clear than, you were following the guidance in the "In native Java projects" section of the README here, correct? Just want to make sure before I dig further.

**Comment by bmorris591** [comment]
Yes - I had the setup working with the previous version (1.1.2), but on updating to 1.2.0 it refused to compile.

I now have it working by using Clojure-Java interop directly:

``` java
static {
    final IFn require = Clojure.var("clojure.core", "require");
    require.invoke(read("uap-clj.core"));
    require.invoke(read("clojure.walk"));

    final IFn userAgentResolver = Clojure.var("uap-clj.core", "useragent");
    final IFn stringifyKeys = Clojure.var("clojure.walk", "stringify-keys");

    USER_AGENT_RESOLVER = userAgent -> {
        @SuppressWarnings("unchecked")
        final Map<String, Map<String, String>> data = (Map<String, Map<String, String>>) stringifyKeys.invoke(userAgentResolver.invoke(userAgent));
        return data;
    };
}

private static final Function<String, Map<String, Map<String, String>>> USER_AGENT_RESOLVER;
```

This seems to work fine - I get a `Map` containing the three parsed items.

**Comment by russellwhitaker** [comment]
Nicely illustrative Java snippet @bmorris591 . OK, I think the issue can be addressed with an `:aot :all` in the project manifest and a push to Clojars; I'll take care of that today or tomorrow and let you know (need to make sure some downstream dependencies play well with that change.)

**Comment by russellwhitaker** [comment]
@bmorris591 sorry for the delay; OK, I've pushed out a new artifact (v1.2.2) which fixes the problem. Here's the dependency snippet for your POM files:

``` xml
<dependency>
  <groupId>uap-clj</groupId>
  <artifactId>uap-clj</artifactId>
  <version>1.2.2</version>
</dependency>
```
