### ISSUE TITLE
Gradle Error

### ISSUE THREAD

**Issue by sebastinakash** [russellwhitaker/uap-clj#35]
What went wrong:
Could not resolve all dependencies for configuration ':crmweb:compile'.

Could not find group:uap-clj, module:uap-clj, version:1.3.1.
Required by:
com.myntra:crmweb:1.0
compile "uap-clj:uap-clj:1.3.1"

**Comment by russellwhitaker** [comment]
You need to add Clojars as a repository to your Gradle build file @sebastinakash .
