### ISSUE TITLE
Released versions include test resources

### ISSUE THREAD

**Issue by sfnelson** [russellwhitaker/uap-clj#40]
The released artifact for 1.3.3 is 1.2M and includes a lot of extraneous files, such as tests, test resources, docs, and classfiles from upstream dependencies. Here's a selection of files that should not be in the release artifact:

```
clojure/tools/logging/impl/Logger.class
environ/core__init.class
flatland/ordered/map/OrderedMap$fn__294.class
immuconf/config__init.class
CONTRIBUTING.md
tests/test.js
test_resources/additional_os_tests.yaml
```

Including class-files for third party dependencies is particularly problematic for downstream users as they may not be using the same dependency versions.

**Comment by russellwhitaker** [comment]
@sfnelson sorry for not having had eyes on this the last year. I'm planning to revisit this project soon to overhaul it systematically, and so I'll roll this issue into the work. Thanks very much for bringing it to my attention!
