### ISSUE TITLE
uap-clj.device/device throws on funny UA strings

### ISSUE THREAD

**Issue by tomconnors** [russellwhitaker/uap-clj#45]
I recently had a strange UA string come in: 

Mozilla/5\\.0 \\(Linux; Android 9; SM\\-N950U\\) AppleWebKit/537\\.36 \\(KHTML, like Gecko\\) Chrome/93\\.0\\.4554\\.0 Mobile Safari/537\\.36

That's how the server received it - with escapes for dots and parens. uap-clj throws when trying to get a device out of that:
``` clojure
(uap-clj.device/device "Mozilla/5\\.0 \\(Linux; Android 9; SM\\-N950U\\) AppleWebKit/537\\.36 \\(KHTML, like Gecko\\) Chrome/93\\.0\\.4554\\.0 Mobile Safari/537\\.36")

Execution error (IllegalArgumentException) at java.util.regex.Matcher/appendExpandedReplacement (Matcher.java:1020).
character to be escaped is missing
```

I don't know if it's uap-clj's job to handle unusual UA strings like that, but I thought I'd make this issue in case other people see something similar.

**Comment by russellwhitaker** [comment]
I ran this through the latest release (`v1.4.1`, which I put out yesterday) and can repro. I have a neutral opinion of where this should be handled; what did you yourself end up doing? Catching and handling `IllegalArgumentException`? I'd be open to pull requests, if you're interested in adding some relevant error handling.
