### ISSUE TITLE
Split Hive functionality into separate lib

### ISSUE THREAD

**Issue by leifp** [russellwhitaker/uap-clj#6]
Pulling in all of hadoop-core and Hive as dependencies is somewhat irksome for users that just want the parsing facilities.

**Comment by russellwhitaker** [comment]
@leifp This work was motivated primarily to support Hadoop/Hive use cases (see the emphasis in the top level README). However, if you're genuinely interested in using this yourself, please let me know, and I'll refactor accordingly: I'll move Hadoop/Hive functionality - with its ASF project dependencies - into a separate, new uap-clj-hive repo, no problem. You're actually interested in using the parser, yes?

**Comment by russellwhitaker** [comment]
@leifp I have now removed the Hadoop Hive UDF dependencies & code, and will be committing all that to a separate repo called 'uap-clj-hiveudf' which depends on _this_ library. Let me know if you find this useful; closing issue now.
